apis/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('class', get_class, name='api_get_all_class'),
    path('property_type', get_property_type_from_class, name='api_get_property_type_from_class'),
    path('instance', get_instance_from_class, name='api_get_instance_from_class'),
    path('instance/<int:instance_id>', get_instance, name='api_get_instance'),
    path('instance/random_from_class', get_random_instance_from_class, name='api_get_random_instance_from_class')
]

shido/urls.py
import logging

from decouple import config
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from users.views import register, logout_and_redirect

logger = logging.getLogger(__name__)

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', logout_and_redirect, name='logout'),
    # path('register/', register, name='register'),
    path('', include('apps.urls')),
    path('users/', include('users.urls')),
    path('api/', include('apis.urls'))
]

if config('ENABLE_DJANGO_ADMIN', cast=bool, default=False):
    urlpatterns.append(path('admin/', admin.site.urls))

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schema_view = get_schema_view(
    openapi.Info(
        title="Shido API",
        default_version='v1',
        description="API for Shido"
    ),
    public=True,
    permission_classes=[permissions.AllowAny]
)

debug_view = [
    # REST Framework's login and logout view
    path('api-auth/', include('rest_framework.urls')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    urlpatterns += debug_view
    logger.debug(f"Debug view is enabled.")
    logger.debug(f"Enabled debug URL patterns: ")
    for url in debug_view:
        logger.debug(f" {url}")

apps/models.py
from django.db import models


class Class(models.Model):
    """
    Class that will contain instances
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Instance(models.Model):
    """
    Instance that's in class
    """
    name = models.CharField(max_length=100)
    class_instance = models.ForeignKey(Class, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def have_wiki(self):
        """
        Check if the instance can have wiki
        :return: True if the instance can have wiki, False if not
        """
        try:
            title = ObjectPropertyRelation.objects.get(instance_object_id=self.id, property_type__name='wikiTitle').raw_value
            content = ObjectPropertyRelation.objects.get(instance_object_id=self.id, property_type__name='wikiContent').raw_value
            image = ObjectPropertyRelation.objects.get(instance_object_id=self.id, property_type__name='wikiImage').raw_value
            return {
                "title": title,
                "content": content,
                "image": image
            }
        except:
            return False


RAW_TYPE_CHOICES = (
    ('string', 'String'),
    ('number', 'Integer'),
    ('float', 'Float'),
    ('boolean', 'Boolean'),
    ('date', 'Date'),
    ('datetime', 'Date Time'),
    ('markdown', 'Markdown'),
    ('image', 'Image'),
    ('file', 'File'),
    ('instance', 'Instance'),
    ('instance_list', 'Instance List'),
    ('json', 'JSON'),
    ('class', 'Class'),
    ('url', 'URL')
)

type_limitation_template = {
    "string": {
        "min_length": 0,
        "max_length": 255
    },
    "number": {
        "min_value": -2147483648,
        "max_value": 2147483647
    },
    "float": {
        "min_value": -2147483648,
        "max_value": 2147483647,
        "decimal_places": 2
    },
    "boolean": {},
    "date": {},
    "datetime": {},
    "markdown": {},
    "image": {},
    "file": {},
    "instance": {
        "class_id": 0
    },
    "instance_list": {
        "allow_class_id_list": []
    },
    "json": {
        "initial_json": {}
    },
    "class": {},
    "url": {}
}


class PropertyType(models.Model):
    """
    Property of the instance
    """
    name = models.CharField(max_length=100)
    class_instance = models.ForeignKey(Class, on_delete=models.CASCADE)
    # raw type is the type that the program will be rendered
    # since in database we can contain only some basic types like string, int, float, etc.
    # but sometime we want to render it as a date, markdown, image, etc.
    # this type the program will know how to render it
    raw_type = models.CharField(max_length=100, choices=RAW_TYPE_CHOICES)
    # limitation is the limitation of the property and will store in JSON format
    # due to the variety of the limitation
    # example of limitation:
    #  - min and max value of number
    #  - min and max length of string
    # this will specify the format by the program
    limitation = models.JSONField(default=dict, blank=True)

    def __str__(self):
        return self.name


class ObjectPropertyRelation(models.Model):
    """
    Connect instance and property
    """
    instance_object = models.ForeignKey(Instance, on_delete=models.CASCADE)
    property_type = models.ForeignKey(PropertyType, on_delete=models.CASCADE)
    # raw value will passed by the program to the frontend to render the real value
    raw_value = models.CharField(max_length=1000000)

    def __str__(self):
        return str(self.instance_object) + ' - ' + str(self.property_type)

templates/apps/property_type/create.html
{% extends "apps/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create a new property type{% endblock %}

{% block styles %}

{% endblock %}

{% block header %}
    <p class="header-title">
        Create a new property type
    </p>
{% endblock %}

{% block content %}
    <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'apps_property_type_list' %}">Property Type</a></li>
            <li class="breadcrumb-item active" aria-current="page">Create</li>
        </ol>
    </nav>
    <h1 style="padding-top: 1rem; padding-bottom: 1rem;">Create a new property type</h1>
    <p></p>
    <p>Note : Some name are reserved and cannot be used as property type name since they are used by the wiki system.</p>
    <ul>
    {% for name in wiki_property_type_list %}
        <li>{{ name }}</li>
    {% endfor %}
    </ul>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
{% endblock %}

{% block scripts %}
<script>
    const typeLimitationTemplate = {
        "string": {
            "min_length": 0,
            "max_length": 255
        },
        "number": {
            "min_value": -2147483648,
            "max_value": 2147483647
        },
        "float": {
            "min_value": -2147483648,
            "max_value": 2147483647,
            "decimal_places": 2
        },
        "boolean": {},
        "date": {},
        "datetime": {},
        "markdown": {},
        "image": {},
        "file": {},
        "instance": {
            "class_id": 0
        },
        "instance_list": {
            "allow_class_id_list": []
        },
        "json": {
            "initial_json": {}
        },
        "class": {},
        "url": {}
    };

    // limitation text area
    let limitation = document.getElementById("id_limitation");
    let rawType = document.getElementById("id_raw_type");
    
    // on raw type dropdown value change, update the limitation text area
    rawType.addEventListener("change", function() {
        let type = rawType.value;
        limitation.value = JSON.stringify(typeLimitationTemplate[type], null, 4);
    });
    
    // Add string limitation as default
    limitation.value = JSON.stringify(typeLimitationTemplate[rawType.value], null, 4);
</script>
{% endblock %}

templates/apps/property_type/detail.html
{% extends "apps/base.html" %}
{% load static %}

{% block title %}{{ property_type.name }}{% endblock %}

{% block styles %}

{% endblock %}

{% block header %}
    <p class="header-title">
        {{ property_type.name }}
    </p>
{% endblock %}

{% block content %}
    <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'apps_property_type_list' %}">Property Type</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ property_type.name }}</li>
        </ol>
    </nav>
    <h1 style="padding-top: 1rem; padding-bottom: 1rem;">{{ property_type.name }}</h1>
    <p></p>
    <h3>Limitation</h3>
    {% if limitation_list %}
    <ul>
        {% for limitation in limitation_list %}
        <li>{{ limitation.key }} : {{ limitation.value }}</li>
        {% endfor %}
    </ul>
    {% else %}
    <p><i class="mdi mdi-alert-circle-outline"></i> No limitation set</p>
    {% endif %}
{% endblock %}

{% block scripts %}

{% endblock %}

templates/apps/property_type/list.html
{% extends "apps/base.html" %}
{% load static %}

{% block title %}Property Type{% endblock %}

{% block styles %}

{% endblock %}

{% block header %}
    <p class="header-title">
        Property Type
    </p>
{% endblock %}

{% block content %}
    <h1 style="padding-top: 1rem; padding-bottom: 1rem;">Property Type</h1>
    {% if user.is_authenticated %}
    <a href="{% url 'apps_property_type_create' %}" class="btn btn-primary"><i class="mdi mdi-plus" aria-hidden="true" style="font-size: 20px"></i> Create</a>
    {% endif %}
    <p></p>
    <div class="row gy-2">
        {% for property in all_property_type %}
        <div class="col-md-4">
            <div class="element-card-wrapper">
                <div class="element-card-background" style="background: url({% static 'img/login.jpg' %}) center center / cover no-repeat; width: 100%; height: 100%; border-radius: 0.25rem;">
                    <div class="element-card-body">
                        <h5 class="card-title">{{ property.name }}</h5>
                        <p class="card-text mb-0">ID : {{ property.id }}</p>
                        <p class="card-text mb-0">Class : <a href="{% url 'apps_class_detail' property.class_instance.id %}">{{ property.class_instance.name }}</a></p>
                        <p class="card-text">Raw type : {{ property.get_raw_type_display }}</p>
                        <a href="{% url 'apps_property_type_detail' property.id %}" class="btn btn-primary btn-sm"><i class="mdi mdi-information" aria-hidden="true" style="font-size: 15px"></i> Detail</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

{% block scripts %}

{% endblock %}